name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  validate-pr:
    name: Validate PR Format
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Check PR title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^Feature\s.+'
          allowed_prefixes: "Feature"
          prefix_case_sensitive: true
          min_length: 10
          max_length: 100

      - name: Check PR description
        uses: JJ/github-pr-contains-action@releases/v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bodyContains: "- "

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [validate-pr]
    if: github.event_name == 'pull_request' || success()

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [validate-pr]
    if: github.event_name == 'pull_request' || success()

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build-and-test, lint]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: sa-project-backend:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
